version: "3.8"

services:
  backend:
    build:
      context: .
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    volumes:
      - "./:/app"
    depends_on:
      - db
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

volumes:
  postgresdata:
